### ISSUE TITLE
Add more model parameters

### ISSUE THREAD

**Issue by V3lop5** [NOWUM/EnSysMod#131]
**Describe the solution you'd like**
It should be possible to override more parameters then just the yearly_limit.

**Additional context**
Add possible parameters [here](https://github.com/NOWUM/EnSysMod/blob/main/ensysmod/model/energy_model_parameter.py) and integrate them [here](https://github.com/NOWUM/EnSysMod/blob/3a541054c5700db6df5b9918760e2082006b51df/ensysmod/core/fine_esm.py#L14).

**Comment by jr-hartono** [comment]
Done on PR #132
