### ISSUE TITLE
Add database models for energy model

### ISSUE THREAD

**Issue by V3lop5** [NOWUM/EnSysMod#32]
**Describe the solution you'd like**
- [x] Add `energy_model`
  - name
  - description
  - ref_dataset
  - yearly_co2_limit
- [x] Add schemas
- [x] Add CRUD
- [x] Add endpoints

**Additional context**
![image](https://user-images.githubusercontent.com/44635962/145380813-0d46fad2-879f-4c50-8844-0975c8a82e6f.png)

**Comment by einfachMel** [comment]
- [x] Add Unit Test
